"""Generate the schema, data dictionary and TypeScript contract from one definition."""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from setsawa.core import FIELDS, write_json

descriptions = {
    "record_id": "Content-addressed dataset record ID; not a verified person ID. SHA-256 of the nine normalized source-content fields.",
    "masked_id": "Source identifier, preserving three digits, six literal x characters and four digits. Not unique; never reconstruct hidden digits.",
    "full_name_th": "Thai name as transcribed, with conservative Unicode NFC and whitespace normalization. No identity matching.",
    "score_adjustment_reported": "Integer adjustment reported by the source; not an independently verified examination result.",
    "agency_name_th": "Agency label transcribed from the source. Abbreviations are preserved.",
    "source_status_text": "Verbatim-normalized first status column (source claim, not project verification).",
    "district_name_th": "District label as reported in the source. Scope by province_id.",
    "province_name_th": "Province label as reported in the document and row.",
    "source_location_basis_text": "Source author's stated basis for location/agency confirmation. Not independently checked here.",
    "source_verification_status_text": "Second status column as reported by the source. Does not verify allegations or establish wrongdoing.",
    "province_id": "Hash of the source province label; not an official administrative code.",
    "district_id": "Hash of the ordered province and district labels; not an official administrative code.",
    "agency_location_id": "Hash of province, district and agency labels; a source-label group, not a verified organization ID.",
}
properties = {}
for key in ["record_id", *FIELDS, "province_id", "district_id", "agency_location_id"]:
    spec = {"type": "integer" if key == "score_adjustment_reported" else "string", "description": descriptions[key]}
    if spec["type"] == "string":
        spec["minLength"] = 1
    if key == "score_adjustment_reported":
        spec.update({"minimum": 1, "maximum": 78})
    if key == "masked_id":
        spec["pattern"] = "^[0-9]{3}x{6}[0-9]{4}$"
    for id_field, prefix in {"record_id": "rec", "province_id": "province", "district_id": "district", "agency_location_id": "agency"}.items():
        if key == id_field:
            spec["pattern"] = "^" + prefix + "_[a-f0-9]{64}$"
    properties[key] = spec
schema = {"$schema": "https://json-schema.org/draft/2020-12/schema", "$id": "https://raw.githubusercontent.com/johnnysins24/SetSawa/v1.0.0/schemas/records.schema.json", "title": "SetSawa record v1.0.0", "type": "object", "additionalProperties": False, "required": list(properties), "properties": properties}
write_json(ROOT / "schemas/records.schema.json", schema)
lines = ["// Generated by scripts/generate_contract.py. Do not edit by hand.", "export interface SetSawaRecord {"]
for key, spec in properties.items():
    lines.extend(["  /** " + spec["description"] + " */", "  " + key + ": " + ("number" if spec["type"] == "integer" else "string") + ";"])
lines.append("}")
(ROOT / "schemas/records.d.ts").write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
