// Generated by scripts/generate_contract.py. Do not edit by hand.
export interface SetSawaRecord {
  /** Content-addressed dataset record ID; not a verified person ID. SHA-256 of the nine normalized source-content fields. */
  record_id: string;
  /** Source identifier, preserving three digits, six literal x characters and four digits. Not unique; never reconstruct hidden digits. */
  masked_id: string;
  /** Thai name as transcribed, with conservative Unicode NFC and whitespace normalization. No identity matching. */
  full_name_th: string;
  /** Integer adjustment reported by the source; not an independently verified examination result. */
  score_adjustment_reported: number;
  /** Agency label transcribed from the source. Abbreviations are preserved. */
  agency_name_th: string;
  /** Verbatim-normalized first status column (source claim, not project verification). */
  source_status_text: string;
  /** District label as reported in the source. Scope by province_id. */
  district_name_th: string;
  /** Province label as reported in the document and row. */
  province_name_th: string;
  /** Source author's stated basis for location/agency confirmation. Not independently checked here. */
  source_location_basis_text: string;
  /** Second status column as reported by the source. Does not verify allegations or establish wrongdoing. */
  source_verification_status_text: string;
  /** Hash of the source province label; not an official administrative code. */
  province_id: string;
  /** Hash of the ordered province and district labels; not an official administrative code. */
  district_id: string;
  /** Hash of province, district and agency labels; a source-label group, not a verified organization ID. */
  agency_location_id: string;
}
